#MakeFile for Hashcode 
#
#Aaron Svedsen, 4/23

# PROG =
OBJS = bag.o
LIBS =

MAKE = make
CC = gcc
CFLAGS = -Wall -pedantic -std=c11 -ggdb

# I have no tester program
# $(PROG): $(OBJS)
#       $(CC) $(CFLAGS) $^ $(LIBS) -o $@

bag.o: bag.h

clean:
	rm -f *~
	rm -f *.o
