#MakeFile for Hashcode Testcode
#
#Aaron Svedsen, 4/23

CC = gcc
CFLAGS = -Wall -pedantic -std=c11 -ggdb
PROG = listtest.c
OBJS = list.c
list:
	$(CC) $(CFLAGS) $(OBJS) $(PROG) -o list



clean:
	rm -f *~
	rm -f *.o
